# Plot scatterplot for all combinations of PCs
# for AFR and AMR omnibus data

# module load gcc/7.1.0  openmpi/3.1.4  R
# R

library(lattice)
library(data.table)

# setwd("/nv/vol185/T1DGC/USERS/cat7ep/data/multiethnic_imputed/chr_6/omnibus")
# setwd("~/Downloads")
# read in pheno file with sex and case-control info
pheno<- fread("./data/T1DGC_HCE-2021-10-07_CT.phe")
pheno<- pheno[,c(2:4)] # drop duplicate

##########
## AFR ###
##########
AFR<- fread("./data/T1DGC_HCE_pc_AFR.txt") # PCs from Dominika 
AFR_5<- AFR[,c(1,2,5:11)] # keep only first 5 PCs 
#color by sex (male=1, female=2)
AFRPlot<- splom(AFR_5[,5:9], groups=AFR_5$SEX, auto.key=list(space="right",text=c("Male","Female")),
                main="AFR PC Associations by Sex (whole dataset)", xlab="PCs 1-5",ylab="PCs 1-5",
                par.settings = list(superpose.symbol = list(col = c("darkorange", "darkblue"))) 
                )
# color by Case-Control
AFRPlot2<- splom(AFR_5[,5:9], groups=AFR_5$AFF, auto.key=list(space="right",text=c("Control","Case")),
                main="AFR PC Associations by Case-Control (whole dataset)", xlab="PCs 1-5",ylab="PCs 1-5",
                par.settings = list(superpose.symbol = list(col = c("deeppink3", "darkgray"))) 
                )

AFR2<- fread("./data/AFR_pc_033122.txt") # generated by me
AFR2_5<- AFR2[,c(1,2,7:11)]
  AFR2_5$IID<- as.character(AFR2_5$IID)
withSexAFR2<- merge(AFR2_5,pheno,by.x=c("IID"),by.y=c("IID"),all.x=T)
#color by sex (male=1, female=2)
AFR2Plot<- splom(withSexAFR2[,3:7], groups=withSexAFR2$p1, auto.key=list(space="right",text=c("Male","Female")),
                main="AFR PC Associations by Sex (chr6 only)", xlab="PCs 1-5",ylab="PCs 1-5",
                par.settings = list(superpose.symbol = list(col = c("darkorange", "darkblue"))) 
)
# color by Case-Control
AFR2Plot2<- splom(withSexAFR2[,3:7], groups=withSexAFR2$p2, auto.key=list(space="right",text=c("Control","Case")),
                 main="AFR PC Associations by Case-Control (chr6 only)", xlab="PCs 1-5",ylab="PCs 1-5",
                 par.settings = list(superpose.symbol = list(col = c("deeppink3", "darkgray"))) 
)

##########
## AMR ###
##########
AMR<- fread("./data/T1DGC_HCE_pc_AMR.txt") # PCs from Dominika
AMR_5<- AMR[,c(1,2,5:11)] # keep only first 5 PCs 
# color by sex
AMRPlot<- splom(AMR_5[,5:9], groups=AMR_5$SEX, auto.key=list(space="right",text=c("Male","Female")), 
                main="AMR PC Associations by Sex (whole dataset)", xlab="PCs 1-5",ylab="PCs 1-5",
                par.settings = list(superpose.symbol = list(col = c("darkorange", "darkblue"))) 
                )
# color by Case-Control
AMRPlot2<- splom(AMR_5[,5:9], groups=AMR_5$AFF, auto.key=list(space="right",text=c("Control","Case")), 
                main="AMR PC Associations by Case-Control (whole dataset)", xlab="PCs 1-5",ylab="PCs 1-5",
                par.settings = list(superpose.symbol = list(col = c("deeppink3", "darkgray"))) 
                )

AMR2<- fread("./data/AMR_pc_033122.txt") # generated by me
AMR2_5<- AMR2[,c(1,2,7:11)]
AMR2_5$IID<- as.character(AMR2_5$IID)
withSexAMR2<- merge(AMR2_5,pheno,by.x=c("IID"),by.y=c("IID"),all.x=T)
#color by sex (male=1, female=2)
AMR2Plot<- splom(withSexAMR2[,3:7], groups=withSexAMR2$p1, auto.key=list(space="right",text=c("Male","Female")),
                 main="AMR PC Associations by Sex (chr6 only)", xlab="PCs 1-5",ylab="PCs 1-5",
                 par.settings = list(superpose.symbol = list(col = c("darkorange", "darkblue"))) 
)
# color by Case-Control
AMR2Plot2<- splom(withSexAMR2[,3:7], groups=withSexAMR2$p2, auto.key=list(space="right",text=c("Control","Case")),
                  main="AMR PC Associations by Case-Control (chr6 only)", xlab="PCs 1-5",ylab="PCs 1-5",
                  par.settings = list(superpose.symbol = list(col = c("deeppink3", "darkgray"))) 
)

##########
## EUR ###
##########
EUR<- fread("./data/EUR_pc_033122.txt") # generated by me 
EUR_5<- EUR[,c(1,2,5:11)]
EUR_sex<- splom(EUR[,7:11], groups=EUR_5$SEX, auto.key=list(space="right",text=c("Male","Female")), 
               main="EUR PC Associations by Sex (chr6 only)", xlab="PCs 1-5",ylab="PCs 1-5",
               par.settings = list(superpose.symbol = list(col = c("darkorange", "darkblue"))) 
)
EUR_cc<- splom(EUR[,7:11], groups=EUR_5$AFF, auto.key=list(space="right",text=c("Control","Case")), 
                 main="EUR PC Associations by Case-Control (chr6 only)", xlab="PCs 1-5",ylab="PCs 1-5",
                 par.settings = list(superpose.symbol = list(col = c("deeppink3", "darkgray"))) 
)

# just pcs 1 and 2
# EUR_pc1_2_sex<- ggplot(EUR[,7:8],aes(x=EUR$PC1,y=EUR$PC2,col=as.factor(EUR$SEX))) + geom_point()
# EUR_pc1_2_cc<- ggplot(EUR[,7:8],aes(x=EUR$PC1,y=EUR$PC2,col=as.factor(EUR$AFF))) + geom_point()


pdf("/nv/vol185/T1DGC/USERS/cat7ep/project/figures/omnibusPlots_AFR_AMR_bysex.pdf")
  AFRPlot
  AMRPlot
dev.off()

pdf("/nv/vol185/T1DGC/USERS/cat7ep/project/figures/omnibusPlots_AFR_AMR_byCC.pdf")
  AFRPlot2
  AMRPlot2
dev.off()